[build]
  base = "."
  command = "pnpm install --frozen-lockfile && pnpm --filter @expenses-tracker/frontend build --configuration production"
  publish = "frontend/dist/frontend/browser"

[[redirects]]
  from = "/api/*"
  to = "https://6nj2hj1k-3000.brs.devtunnels.ms/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
