import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const semverPattern = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-(?:0|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*)?(?:\+[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*)?$/;
const generatedModuleComment = '// This file is generated by scripts/version-sync.mjs. Do not edit manually.';

function parseArguments(argumentsList) {
  const mode = argumentsList.find((argument) => argument === '--sync' || argument === '--check');
  const rootIndex = argumentsList.indexOf('--root');
  const root = rootIndex === -1 ? null : argumentsList[rootIndex + 1];

  if (!mode || (rootIndex !== -1 && !root)) {
    throw new Error('Usage: node scripts/version-sync.mjs --sync|--check [--root <workspace-path>]');
  }

  return { mode, root };
}

function readJson(path) {
  try {
    return JSON.parse(readFileSync(path, 'utf8'));
  } catch (error) {
    throw new Error(`Could not read ${path}: ${error instanceof Error ? error.message : String(error)}`);
  }
}

function packageContent(packageJson, version) {
  return `${JSON.stringify({ ...packageJson, version }, null, 2)}\n`;
}

function generatedModuleContent(version) {
  return `${generatedModuleComment}\nexport const APP_VERSION = '${version}' as const;\n`;
}

function contentMatches(path, expectedContent, errors, workspaceRoot) {
  try {
    if (readFileSync(path, 'utf8').replace(/\r\n/g, '\n') === expectedContent) {
      return true;
    }
  } catch {
    // A missing generated module is also a mismatch.
  }

  errors.push(`${relative(workspaceRoot, path).split(String.fromCharCode(92)).join('/')} is not synchronized with the canonical version.`);
  return false;
}

function synchronizeFile(path, expectedContent) {
  try {
    if (readFileSync(path, 'utf8') === expectedContent) {
      return;
    }
  } catch {
    // The file will be created below.
  }

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, expectedContent);
}

function run() {
  const { mode, root } = parseArguments(process.argv.slice(2));
  const scriptRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
  const workspaceRoot = resolve(root ?? scriptRoot);
  const rootPackagePath = join(workspaceRoot, 'package.json');
  const rootPackage = readJson(rootPackagePath);
  const version = rootPackage.version;

  if (typeof version !== 'string' || !semverPattern.test(version)) {
    throw new Error(`The canonical version in package.json must be a valid Semantic Version; received ${JSON.stringify(version)}.`);
  }

  const targets = [
    { path: join(workspaceRoot, 'backend', 'package.json'), content: null },
    { path: join(workspaceRoot, 'frontend', 'package.json'), content: null },
    { path: join(workspaceRoot, 'frontend', 'src', 'app', 'generated', 'app-version.ts'), content: generatedModuleContent(version) }
  ].map((target) => ({
    ...target,
    content: target.content ?? packageContent(readJson(target.path), version)
  }));

  if (mode === '--sync') {
    for (const target of targets) {
      synchronizeFile(target.path, target.content);
    }
    process.stdout.write(`Synchronized release version ${version}.\n`);
    return;
  }

  const errors = [];
  for (const target of targets) {
    contentMatches(target.path, target.content, errors, workspaceRoot);
  }

  if (errors.length > 0) {
    throw new Error(`Version synchronization check failed:\n- ${errors.join('\n- ')}`);
  }

  process.stdout.write(`Release version ${version} is synchronized.\n`);
}

try {
  run();
} catch (error) {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
  process.exitCode = 1;
}
