import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { afterEach, describe, expect, it } from 'vitest';

const repositoryRoot = resolve(process.cwd(), '..');
const versionScript = join(repositoryRoot, 'scripts', 'version-sync.mjs');
const temporaryRoots: string[] = [];

function createWorkspace(version: string, backendVersion = '0.0.0', frontendVersion = '0.0.0'): string {
  const root = mkdtempSync(join(tmpdir(), 'expenses-version-'));
  temporaryRoots.push(root);

  for (const relativePath of ['backend/package.json', 'frontend/package.json']) {
    mkdirSync(dirname(join(root, relativePath)), { recursive: true });
  }

  writeFileSync(join(root, 'package.json'), JSON.stringify({ name: 'fixture', version, private: true }, null, 2));
  writeFileSync(join(root, 'backend/package.json'), JSON.stringify({ name: 'backend', version: backendVersion }, null, 2));
  writeFileSync(join(root, 'frontend/package.json'), JSON.stringify({ name: 'frontend', version: frontendVersion }, null, 2));
  return root;
}

function runVersionScript(root: string, mode: '--sync' | '--check') {
  return spawnSync(process.execPath, [versionScript, mode, '--root', root], {
    encoding: 'utf8'
  });
}

afterEach(() => {
  for (const root of temporaryRoots.splice(0)) {
    rmSync(root, { recursive: true, force: true });
  }
});

describe('version-sync', () => {
  it('propagates a valid canonical SemVer version to package manifests and the generated frontend module', () => {
    const root = createWorkspace('1.2.3');

    const result = runVersionScript(root, '--sync');

    expect(result.status, result.stderr).toBe(0);
    expect(JSON.parse(readFileSync(join(root, 'backend/package.json'), 'utf8')).version).toBe('1.2.3');
    expect(JSON.parse(readFileSync(join(root, 'frontend/package.json'), 'utf8')).version).toBe('1.2.3');
    expect(readFileSync(join(root, 'frontend/src/app/generated/app-version.ts'), 'utf8')).toBe(
      "// This file is generated by scripts/version-sync.mjs. Do not edit manually.\nexport const APP_VERSION = '1.2.3' as const;\n"
    );
  });

  it('reports every stale generated or package version without changing files', () => {
    const root = createWorkspace('1.2.3', '9.9.9', '8.8.8');
    const generatedPath = join(root, 'frontend/src/app/generated/app-version.ts');
    mkdirSync(dirname(generatedPath), { recursive: true });
    writeFileSync(generatedPath, "export const APP_VERSION = '7.7.7' as const;\n");

    const result = runVersionScript(root, '--check');

    expect(result.status).not.toBe(0);
    expect(result.stderr).toContain('backend/package.json');
    expect(result.stderr).toContain('frontend/package.json');
    expect(result.stderr).toContain('frontend/src/app/generated/app-version.ts');
    expect(JSON.parse(readFileSync(join(root, 'backend/package.json'), 'utf8')).version).toBe('9.9.9');
  });

  it('accepts synchronized targets checked out with Windows CRLF line endings', () => {
    const root = createWorkspace('1.2.3');
    expect(runVersionScript(root, '--sync').status).toBe(0);

    for (const relativePath of [
      'backend/package.json',
      'frontend/package.json',
      'frontend/src/app/generated/app-version.ts'
    ]) {
      const path = join(root, relativePath);
      writeFileSync(path, readFileSync(path, 'utf8').replace(/\n/g, '\r\n'));
    }

    const result = runVersionScript(root, '--check');

    expect(result.status, result.stderr).toBe(0);
  });

  it('rejects an invalid canonical version before it can be propagated', () => {
    const root = createWorkspace('next-release');

    const result = runVersionScript(root, '--sync');

    expect(result.status).not.toBe(0);
    expect(result.stderr).toContain('valid Semantic Version');
    expect(JSON.parse(readFileSync(join(root, 'backend/package.json'), 'utf8')).version).toBe('0.0.0');
  });
});
